modLoader="javafml"
loaderVersion="[31,)"
license="MIT"
[[mods]]
modId="entityculling"
version="1.2.2"
displayName="EntityCulling"
authors="tr7zw"
description='''
Using async raytracing to hide Tile-/Entities that are hidden behind solid blocks.
'''
[[dependencies.entityculling]] #optional
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="CLIENT"
# Here's another dependency
[[dependencies.entityculling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="CLIENT"
